"""One-time setup: create the Notion database the drop writes into.

Usage
-----
    export NOTION_API_KEY=ntn_xxx                 # or put it in .streamlit/secrets.toml
    python scripts/setup_notion.py --list-parents  # show pages you can build inside
    python scripts/setup_notion.py --parent-page <page url or id>

It creates a database whose schema the app expects:

    Name      (title)   - the label the uploader types
    Document  (files)   - the uploaded file itself
    Approved  (checkbox)- your moderation switch (public site only shows ticked rows)

The parent page must be shared with your Notion integration first
(page menu ... -> Connect to -> your integration), otherwise Notion answers 404.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

import requests

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from filedrop.notion_client import API_VERSION, NOTION_BASE  # noqa: E402

ID_RE = re.compile(r"([0-9a-fA-F]{32}|[0-9a-fA-F-]{36})")


def parse_id(value: str) -> str:
    """Accept a raw uuid, a dashed uuid, or a pasted Notion url."""
    text = (value or "").strip()
    if not text:
        return ""
    match = ID_RE.search(text)
    if not match:
        return text
    raw = match.group(1).replace("-", "").lower()
    return f"{raw[0:8]}-{raw[8:12]}-{raw[12:16]}-{raw[16:20]}-{raw[20:32]}"


def _headers(token: str) -> dict[str, str]:
    return {
        "Authorization": f"Bearer {token}",
        "Notion-Version": API_VERSION,
        "Content-Type": "application/json",
    }


def list_parents(token: str, base_url: str) -> int:
    response = requests.post(
        f"{base_url}/v1/search",
        headers=_headers(token),
        json={"filter": {"property": "object", "value": "page"}, "page_size": 25},
        timeout=30,
    )
    if response.status_code >= 400:
        print(f"Notion said {response.status_code}: {response.text[:300]}")
        return 1
    pages = response.json().get("results", [])
    if not pages:
        print(
            "No pages are shared with this integration yet.\n"
            "In Notion: open a page -> ... -> Connect to -> your integration, then re-run."
        )
        return 1
    print("Pages you can create the database inside:\n")
    for page in pages:
        title = "Untitled"
        for prop in (page.get("properties") or {}).values():
            if prop.get("type") == "title" and prop.get("title"):
                title = "".join(t.get("plain_text", "") for t in prop["title"]) or title
                break
        print(f"  {title}\n    {page.get('url')}\n    id: {page.get('id')}")
    print("\nThen:  python scripts/setup_notion.py --parent-page <id or url>")
    return 0


def create_workspace_page(token: str, base_url: str, title: str) -> dict:
    """Create a top-level page so the drop is not nested inside existing work."""
    response = requests.post(
        f"{base_url}/v1/pages",
        headers=_headers(token),
        json={
            "parent": {"type": "workspace", "workspace": True},
            "properties": {"title": {"title": [{"type": "text", "text": {"content": title}}]}},
        },
        timeout=60,
    )
    if response.status_code >= 400:
        raise SystemExit(
            f"Creating the page failed ({response.status_code}): {response.text[:400]}"
        )
    return response.json()


def create_database(token: str, base_url: str, parent_id: str, title: str) -> dict:
    payload = {
        "parent": {"type": "page_id", "page_id": parent_id},
        "title": [{"type": "text", "text": {"content": title}}],
        "initial_data_source": {
            "properties": {
                "Name": {"title": {}},
                "Document": {"files": {}},
                "Approved": {"checkbox": {}},
            }
        },
    }
    response = requests.post(
        f"{base_url}/v1/databases", headers=_headers(token), json=payload, timeout=60
    )
    if response.status_code >= 400:
        raise SystemExit(
            f"Creating the database failed ({response.status_code}): {response.text[:400]}\n"
            "If it says 404, share the parent page with your integration "
            "(page menu ... -> Connect to -> your integration)."
        )
    return response.json()


def data_source_id_of(database: dict) -> str:
    sources = database.get("data_sources") or []
    if sources:
        return sources[0].get("id", "")
    return database.get("data_source_id") or ""


def write_secrets(path: str, token: str, data_source_id: str, *, require_approval: bool) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        "# Generated by scripts/setup_notion.py\n"
        f'NOTION_API_KEY = "{token}"\n'
        f'NOTION_DATA_SOURCE_ID = "{data_source_id}"\n'
        f"REQUIRE_APPROVAL = {'true' if require_approval else 'false'}\n"
        'SITE_NAME = "Community File Drop"\n'
        "# UPLOAD_PASSCODE = \"\"        # set a shared word to stop random uploads\n"
        "# MAX_UPLOAD_MB = 20           # Notion's hard ceiling for a single-part upload\n",
        encoding="utf-8",
    )
    print(f"\nWrote {target} - keep it out of git.")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Create the Notion database for the file drop.")
    parser.add_argument("--parent-page", help="Notion page id or url to create the database inside")
    parser.add_argument(
        "--workspace-parent",
        action="store_true",
        help="Create a new top-level page for the drop, then build the database inside it",
    )
    parser.add_argument("--title", default="Community File Drop", help="Database title")
    parser.add_argument("--list-parents", action="store_true", help="Show pages shared with the integration")
    parser.add_argument("--base-url", default=os.environ.get("NOTION_API_BASE", NOTION_BASE),
                        help="Override the API host (used by tests)")
    parser.add_argument("--write-secrets", help="Path to write .streamlit/secrets.toml")
    parser.add_argument("--write-env", help="Path to write a plain .env file")
    parser.add_argument("--no-approval", action="store_true", help="Publish uploads immediately")
    args = parser.parse_args(argv)

    token = os.environ.get("NOTION_API_KEY", "").strip()
    if not token:
        print("Set NOTION_API_KEY first (Notion -> Settings -> Connections -> your integration).")
        return 2

    if args.list_parents:
        return list_parents(token, args.base_url)

    parent_id = ""
    if args.workspace_parent:
        page = create_workspace_page(token, args.base_url, args.title)
        parent_id = page.get("id", "")
        print(f"Created page: {page.get('url')}")
        print(f"  page id: {parent_id}")
    elif args.parent_page:
        parent_id = parse_id(args.parent_page)
    if not parent_id:
        parser.error("--parent-page is required (or use --workspace-parent / --list-parents)")

    database = create_database(token, args.base_url, parent_id, args.title)
    ds_id = data_source_id_of(database)
    if not ds_id:
        print("Notion returned no data source id:")
        print(json.dumps(database, indent=2)[:2000])
        return 1

    print("Database created.")
    print(f"  database id      : {database.get('id')}")
    print(f"  database url     : {database.get('url')}")
    print(f"  data source id   : {ds_id}")
    print("\nPut these in .streamlit/secrets.toml (and in the host's secrets when deployed):")
    print(f'  NOTION_API_KEY = "{token[:8]}..."     # your integration token')
    print(f'  NOTION_DATA_SOURCE_ID = "{ds_id}"')
    print("  REQUIRE_APPROVAL = " + ("false" if args.no_approval else "true"))
    print("\nUpload page: app.py     Download page: pages/1_Download.py")

    if args.write_secrets:
        write_secrets(
            args.write_secrets, token, ds_id, require_approval=not args.no_approval
        )
    if args.write_env:
        Path(args.write_env).write_text(
            f"NOTION_API_KEY={token}\nNOTION_DATA_SOURCE_ID={ds_id}\n"
            f"REQUIRE_APPROVAL={'false' if args.no_approval else 'true'}\n",
            encoding="utf-8",
        )
        print(f"Wrote {args.write_env}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
